name: TorrentFileCreator
description: A sample Chrome packaged application
dependencies:
  chrome: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore.git
  hetimafile:
    git: https://github.com/kyorohiro/dart_hetimafile.git
  hetimagit:
    git: https://github.com/kyorohiro/dart_hetimagit.git
  hetimatorrent:
    path: ../../
transformers:
- chrome
- $dart2js:
    csp: true
