name: hetimatorrent
version: 0.0.1
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore.git
  hetimafile:
    git: https://github.com/kyorohiro/dart_hetimafile.git
  hetimanet:
    git: https://github.com/kyorohiro/dart_hetimanet.git
  unittest: 0.11.6
