name: TorrentFileParser
description: A sample Chrome packaged application
dependencies:
  chrome: any
  hetimacore:
    path: ../../../dart_hetimacore
  hetimanet:
    path: ../../../dart_hetimanet
  hetimatorrent:
    path: ../../
transformers:
- chrome
